// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ahoimmykvjkeebqmhgsa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFob2ltbXlrdmprZWVicW1oZ3NhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU4NDM1NjQsImV4cCI6MjA3MTQxOTU2NH0.8jf_RDd0bdEdS9OXjbuvkGuAwAZRVeSyirCfx0JXLmQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});